uncomment eslint && remove airbnb
=====================================================
=====================================================
=====================================================

the below errors / warnings are the kind that I expect from Vue... as oppsed to some thing like "parsing error... unexpected token"

=====================================================
=====================================================
=====================================================

> npm run serve

> csai-data-app@0.1.0 serve /Users/mfekadu/GitHub/web-validate-collect
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 WARNING  Compiled with 2 warnings                                                 6:05:33 PM

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Expected 'v-bind:key' directive to use the variables which are defined by the 'v-for' directive (vue/valid-v-for) at src/views/Validate.vue:12:53:
  10 |           </button>
  11 |           <ul class="file-fields">
> 12 |             <li v-for="(value, key) in currentData" :key="currentData.timestamp">{{key}}:{{value}}</li>
     |                                                     ^
  13 |           </ul>
  14 |         </div>
  15 |       </div>

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Expected to return a value in "bannerColor" computed property (vue/return-in-computed-property) at src/App.vue:61:16:
  59 |     },
  60 |
> 61 |     bannerColor() {
     |                ^
  62 |       switch (this.banner.type) {
  63 |
  64 |         case "default":

1 error found.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://172.31.98.239:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

=====================================================
=====================================================
=====================================================

The below errors the the kind that I did not expect... I suppose that's because Airbnb doesn't use Vue??? ¯\_(ツ)_/¯

=====================================================
=====================================================
=====================================================

>
>
> rm -rf node_modules/
>
> npm install

> fsevents@1.2.9 install /Users/mfekadu/GitHub/web-validate-collect/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
[fsevents] Success: "/Users/mfekadu/GitHub/web-validate-collect/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> grpc@1.20.3 install /Users/mfekadu/GitHub/web-validate-collect/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "/Users/mfekadu/GitHub/web-validate-collect/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node" is installed via remote

> yorkie@2.0.0 install /Users/mfekadu/GitHub/web-validate-collect/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

> core-js@2.6.9 postinstall /Users/mfekadu/GitHub/web-validate-collect/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> protobufjs@6.8.8 postinstall /Users/mfekadu/GitHub/web-validate-collect/node_modules/protobufjs
> node scripts/postinstall

added 1474 packages from 988 contributors and audited 29393 packages in 14.464s
found 0 vulnerabilities

> npm run serve

> csai-data-app@0.1.0 serve /Users/mfekadu/GitHub/web-validate-collect
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 WARNING  Compiled with 12 warnings                                                6:07:30 PM

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: The keyword 'export' is reserved at src/mixins/parser.js:1:1:
> 1 | export default {
    | ^
  2 |   data() {
  3 |     return {
  4 |       fileStructures: {

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: The keyword 'import' is reserved at src/main.js:1:1:
> 1 | import Vue from 'vue';
    | ^
  2 | import App from './App.vue';
  3 | import router from './router';
  4 | import store from './store';

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: The keyword 'import' is reserved at src/registerServiceWorker.js:3:1:
  1 | /* eslint-disable no-console */
  2 |
> 3 | import { register } from 'register-service-worker';
    | ^
  4 |
  5 | if (process.env.NODE_ENV === 'production') {
  6 |   register(`${process.env.BASE_URL}service-worker.js`, {

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: The keyword 'import' is reserved at src/router.js:1:1:
> 1 | import Vue from "vue";
    | ^
  2 | import Router from "vue-router";
  3 | import Auth from "./views/Auth.vue";
  4 |

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: The keyword 'import' is reserved at src/store.js:1:1:
> 1 | import Vue from "vue";
    | ^
  2 | import Vuex from "vuex";
  3 | import router from "./router";
  4 | const firebase = require("firebase");

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/App.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div id="app">
  3 |     <div
  4 |       v-if="showMenu"

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Auth.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="auth">
  3 |     <div class="auth-box">
  4 |       <transition-group tag="div" name="fade-drop" mode="out-in">

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Dashboard.vue:1:1:
> 1 | <template>
    | ^
  2 |   <!-- Under Development Placeholder. Remove when you start working -->
  3 |   <div class="incomplete-box">
  4 |     <img src="../assets/incomplete-feature.svg" alt="incomplete">

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Phrases.vue:1:1:
> 1 | <template>
    | ^
  2 |   <!-- Under Development Placeholder. Remove when you start working -->
  3 |   <div class="incomplete-box">
  4 |     <img src="../assets/incomplete-feature.svg" alt="incomplete">

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Record.vue:1:1:
> 1 | <template>
    | ^
  2 |   <!-- Under Development Placeholder. Remove when you start working -->
  3 |   <div class="incomplete-box">
  4 |     <img src="../assets/incomplete-feature.svg" alt="incomplete">

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Uploads.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div
  3 |     class="page uploads diagonal-background"
  4 |     @dragover.prevent="handleDrag"

1 error found.

Module Warning (from ./node_modules/eslint-loader/index.js):
error: Parsing error: Unexpected token < at src/views/Validate.vue:1:1:
> 1 | <template>
    | ^
  2 |   <div class="page diagonal-background">
  3 |     <div class="loader white-border on-bottom" v-if="loadingData"></div>
  4 |     <transition name="fade-in">

1 error found.

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://172.31.98.239:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.